# Use postgres/example user/password credentials
version: '3.9'

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${SPRING_DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      POSTGRES_DB: ${SPRING_DATASOURCE_BD}
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data
